### PR TITLE
Update to the lazyledger packages instead of tendermint and the cosmos-sdk

### LINKED ISSUE #4: clean up imports
I quickly skimmed through the imports and it seems that the app imports a mixture of lazyledger-core and github.com/tendermint/tendermint.

### PR DESCRIPTION
**Pull request by evan-forbes**
Uses the replace directive to use the latest LazyLedger fork of the cosmos-sdk, along with manually replacing tendermint with lazyledger-core

Closes #4

### CODE REVIEW

**Comment by liamsi** [comment]
Looks good to me! Wondering if we shouldn't merge in the CI changes first?

**Review by tzdybal — COMMENTED** [review]
LGTM.

Is it tested that the `starport scaffolding #1` is working correctly after the whitespace changes?

**Comment by evan-forbes** [comment]
Do you mind elaborating a bit, @tzdybal? I'm not quite sure what `starport scaffolding #1` is. This branch has been tested to start a new chain, but it does not use starport for that.

**Review by liamsi — COMMENTED** [review]
Needs resolving the merge conflicts / rebasing onto master. If CI passes afterwards, I'd approve :-)

**Comment by evan-forbes** [comment]
I'm still trying to figure out the last `make proto-lint` failure, but then it should be g2g

**Comment by evan-forbes** [comment]
Ok, now we're good to go. The only CI failure is because we don't have any tests.

**Review by liamsi — APPROVED** [review]
Thanks Evan! LGTM 👍

**Pull request merged**
